### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by Alexandra21bi2** [nonatalies/WeLoveJavaFX#5]
### Обязательно###
- [ ] Проработка дизайна приложения
- [ ] Проработка дизайна ползунка громкости
- [ ] Техническая реализация ползунка громкости
- [ ] Проработка визуального представления кнопок переключения песен и паузы/воспроизведения
- [ ] Проработка технического аспекта кнопок переключения песен и паузы/воспроизведения
- [ ] Подборка и загрузка треков
- [ ] Проработка дизайна поисковой строки
- [ ] Техническая реализация поисковой строки
- [ ] Техническая реализация поиска песен и их представления в медиаплеере
- [ ] Поиск и загрузка информации об исполнителях
- [ ] Техническая реализация показа информации об исполнителях
- [ ] Визуальное представление кнопок "добавить в избранное", "добавить в плейлист", "повтор трека", "просмотр очереди"
- [ ] Техническая реализация кнопок "добавить в избранное", "добавить в плейлист", "повтор трека", "просмотр очереди"
- [ ] Проработка кнопки "скачивание музыки"
- [ ] Техническая реализация скачивания музыки
- [ ] Графическое представление плейлистов и списков "избранное", "очередь"
- [ ] Техническая реализация составления плейлистов и списков "избранное", "очередь"
- [ ] Покрытие кода тестами
- [ ] Дизайн визуального представления песен в медиаплеере
- [ ] Создание прототипа продукта с минимальным функционалом
- [ ] Тестирование прототипа
### Необязательно###
- [ ] Проработка дизайна кнопки переключения темы
- [ ] Написание кода для кнопки переключения темы
- [ ] Реализация визуального прототипа учетной записи пользователя
- [ ] Техническая реализация создания учетной записи пользователя
- [ ] Подбор текстов песен
- [ ] Техническая реализация демонстрации текста
- [ ] Визуальное представление сортировки песен по жанрам/исполнителям
- [ ] Техническая реализация сортировки песен по жанрам/исполнителям
- [ ] Создание дизайна опции подбора музыки по предпочтениями
- [ ] Написание кода для реализации подбора музыки по предпочтениям
- [ ] Покрытие тестами "необязательных" участков кода
